### ISSUE TITLE
Updates for ComradeBase 0.8

### ISSUE THREAD

**Issue by ptiede** [EHTJulia/ScatteringOptics.jl#26]
From analyzing the code the only thing I saw immediately was that `visibility_point` is now defined as 

```julia

function visibility_point(m::AbstractScatteringModel, p)
  (;U, V, Ti, Fr) = p #extract U, V, time and frequency
  ....
end
```

**Comment by kazuakiyama** [comment]
@annatartaglia I made changes in visibility_point funciton to reflect this change. The related comit is here. I haven't tested whether this change is enough or not. 
https://github.com/EHTJulia/ScatteringOptics.jl/commit/d3b32f61b361cc5d81969169d32ec3056710012f

@ptiede I noticed that `IsPrimitive` and `isprimitive` previously required for `AbstractModel` no longer exist in ComradeBase. I removed that.
https://github.com/EHTJulia/ScatteringOptics.jl/commit/6d26111996e443d36247bf8f70acae79b00c3e9b

**Comment by ptiede** [comment]
Ya that's correct. It's no longer needed

**Comment by kazuakiyama** [comment]
@ptiede 
So, now I updated the documentation and tested the new function. 
https://ehtjulia.github.io/ScatteringOptics.jl/dev/tutorials/gettingstarted

It turns out that it is yet problematic to assume that p always has Fr and Ti. I modified the current implementation in this way, which works with ComradeBase.jl >= v0.8.
```
@inline function visibility_point(skm::ApproximatedScatteringKernel{T,S,N}, p) where {T,S,N}
    U = p.U
    V = p.V
    ν = :Fr in keys(p) ? p.Fr : skm.νref
    return visibility_point_approx(skm.sm, ν2λcm(ν), U, V) + zero(T)im
end
```

Another thing I found is that `convolve` method for Skymodels yet apparently doesn't support 4D IntensityMap. So the current implementation yet only supports the simplest 2D IntensityMap.

**Comment by ptiede** [comment]
We should probably just have `load_fits` load in the Fr. The hack you implemented is probably the best thing to do for now. 
I don't really think this is a Comrade bug, but rather an annoyance since we still don't have full multifrequency support.

**Comment by kazuakiyama** [comment]
Agreed. I would rather wait until multifrequency support gets matured.

**Comment by kazuakiyama** [comment]
Related release: https://github.com/EHTJulia/ScatteringOptics.jl/releases/tag/v0.1.3
